---
driver:
  name: terraform

provisioner:
  name: terraform

platforms:
  - name: ubuntu

transport:
  name: ssh
  ssh_key: put aws-key.pem

verifier:
  name: terraform
  systems:
    - name: default
      backend: ssh
      user: ubuntu      
      hosts_output: public_ip
      key_files:
        - put aws-key.pem
suites:
  - name: default